### ISSUE TITLE
Intel GPU stack be more permissive

### ISSUE THREAD

**Issue by jpm-canonical** [canonical/inference-snaps#130]
https://github.com/canonical/deepseek-r1-snap/blob/c3a12b6d17b28b2d21102249f2fe0140785e5672/stacks/intel-gpu/stack.yaml#L5-L41

Currently we only target this specific set of Intel Battlemage dGPUs. The stack however also works on most other Intel GPUs. Should have rewrite this stack's device compatibility to the following, allowing any Intel GPU?

```
devices:
  all:
    - type: cpu
      architecture: amd64
    # Intel Graphics
    - type: gpu
      vendor-id: 0x8086 # Intel Corporation
```
